version: "3.7"


services:
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: chrome
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/shm:/dev/shm
    shm_size: "2g"
    privileged: true
    network_mode: "service:wg_client"

  wgclient:
    container_name: wgclient
    build: .
    cap_add:
      - NET_ADMIN
    expose:
      - 587/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./generated/:/etc/wireguard/
      - ./scripts/:/comps/
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "/etc/wireguard/setup.sh && sleep infinity"
