version: "3.7"


services:
  wgclient:
    container_name: wgclient
    image: frankpetrilli/boringtun
    cap_add:
      - NET_ADMIN
    expose:
      - 587/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./:/etc/wireguard/
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "/etc/wireguard/setup.sh && sleep infinity"
