version: '3.7'
services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-yttrium
    container_name: qhrome
    cap_add:
      - NET_ADMIN
    volumes: 
      - /dev/shm:/dev/shm
    network_mode: "service:wg_client"
  wg1:
    privileged: true
    image: frankpetrilli/boringtun
    container_name: wg1
    cap_add:
      - NET_ADMIN
    expose:
      - 587/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg1:/etc/wireguard/
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "wg-quick up wg1 && sleep infinity"
    networks:
      - server_network
      - wg1_network

  wg2:
    privileged: true
    image: frankpetrilli/boringtun
    container_name: wg2
    cap_add:
      - NET_ADMIN
    expose:
      - 587/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg2:/etc/wireguard/
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "wg-quick up wg2 && sleep infinity"
    networks:
      - server_network
      - wg2_network

  wg_client:
    privileged: true
    build: ./boringtun-docker
    container_name: wg_client
    ports:
      - "4444:4444"
    depends_on:
      - server
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg_client:/etc/wireguard/
      - ./chromium-quic:/app/
      - ${CHROMIUM_SRC_DIR:?Must set chromium source directory}:/src
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv4.ip_nonlocal_bind=1
    entrypoint: /bin/bash
    command: -c "/etc/wireguard/build-client.sh && /etc/wireguard/setup.sh && sleep infinity"
    extra_hosts:
      server: 10.3.0.4
    networks:
      wg1_network:
      wg2_network:
      #client_network:
      #  ipv4_address: 10.4.0.3

  server:
    container_name: server
    build: ./chromium-quic
    volumes:
      - ${CHROMIUM_SRC_DIR:?Must set chromium source directory}:/src
    networks:
      server_network:
        ipv4_address: 10.3.0.4

networks:
  wg1_network:
    name: wg1_network
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
  wg2_network:
    name: wg2_network
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/16
  server_network:
    name: server_network
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
  client_network:
    name: client_network
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/16
