version: '3.7'
services:
  wg1:
    privileged: true
    image: frankpetrilli/boringtun
    container_name: wg1
    cap_add:
      - NET_ADMIN
    expose:
      - 587/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg1:/etc/wireguard/
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "wg-quick up wg1 && sleep infinity"
    networks:
      - server_network
      - wg1_network

  wg_client:
    privileged: true
    build: ./boringtun-docker
    container_name: wg_client
    depends_on:
      - server
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg_client:/etc/wireguard/
      - ./chromium-quic:/app/
      - ${CHROMIUM_SRC_DIR:?Must set chromium source directory}:/src
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    entrypoint: /bin/bash
    command: -c "/etc/wireguard/build-client.sh && wg-quick up wg1_client && sleep infinity"
    extra_hosts:
      server: 10.3.0.4
    networks:
      - wg1_network

  server:
    container_name: server
    build: ./chromium-quic
    volumes:
      - ${CHROMIUM_SRC_DIR:?Must set chromium source directory}:/src
    networks:
      server_network:
        ipv4_address: 10.3.0.4

networks:
  wg1_network:
    name: wg1_network
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
  
  server_network:
    name: server_network
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
