version: '3.7'
services:

  chrome:
    image: selenium/standalone-chrome-debug
    container_name: chrome
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/shm:/dev/shm
    shm_size: "2g"
    privileged: true
    network_mode: "service:wg_client"

  server:
    container_name: server
    build: server/app
    expose:
      - 80
    networks:
      - server_network
    volumes:
      - ./server/data:/data
    depends_on:
      - wg

  wg:
    privileged: true
    build: client
    container_name: wg
    cap_add:
      - NET_ADMIN
    expose:
      - 1194/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./wg:/etc/wireguard/
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "wg-quick up /etc/wireguard/wg.conf && sleep infinity"
    networks:
      - net1
      - net2
      - server_network

  wg_client:
    privileged: true
    build: client
    container_name: wg_client
    cap_add:
      - NET_ADMIN
    expose:
      - 1194/udp
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ./client:/etc/wireguard/
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    ports:
      - "4444:4444"
      - "9090:7900"
      - "9000:5900"
    entrypoint: /bin/bash
    command: -c "/comps/setup.sh"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    extra_hosts:
      server: 10.3.0.3
    networks:
      - net1
      - net2

networks:
  net2:
    name: net2
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
  server_network:
    name: server_network
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
  net1:
    name: net1
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
